version: '3'

services:
  api:
    build: .
    restart: unless-stopped
    command: npm run start
    ports:
      - '3000:3000'
  nginx:
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf.local:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - api
